### ISSUE TITLE
Decision for dependency injection framework

### ISSUE THREAD

**Issue by danielksan81** [direct-state-transfer/dst-go#10]
The goal of dst-go is provide flexible implementation to make use of different Blockchain networks to set up state-channels as well as to support different communication technologies. Therefore an adapter concept is already implemented with the usage of factories.
To be more flexible in the code base and provide an easier mechanism to provide extensions and alternative implementations, Inversion of Control (IoC) should be established together with the usage of a dependency injection (DI) framework.
In go there are currently 3 DI frameworks existent:
* https://github.com/uber-go/dig
* https://github.com/google/wire
* https://github.com/facebookarchive/inject (archived, out of scope)

Decision should be made for one of the mentioned frameworks which will be used then for wiring the dependencies.

**Comment by manoranjith** [comment]
Issue closed, as it relates to the older implementation which is now archived on [legacy/master](https://github.com/direct-state-transfer/dst-go/tree/legacy/master)
