### ISSUE TITLE
Code coverage report

### ISSUE THREAD

**Issue by danielksan81** [direct-state-transfer/dst-go#11]
The current build process includes unit tests. By running the unit tests, the cover flag is set by default to provide an overview in the output about the current coverage.
An overall report generation is currently missed, which should be added to the current used CI (circleci) environment.
One possible solution for the report can be the usage of https://codecov.io/, which is also providing an integration to circleci by using an orb, see https://circleci.com/blog/making-code-coverage-easy-to-see-with-the-codecov-orb/.

**Comment by manoranjith** [comment]
Issue closed, as it relates to the older implementation which is now archived on [legacy/master](https://github.com/direct-state-transfer/dst-go/tree/legacy/master)
