### ISSUE TITLE
Walk-through unsafe handling of incoming packets 

### ISSUE THREAD

**Issue by MariusVanDerWijden** [direct-state-transfer/dst-go#19]
Currently packets in the walkthrough are handled in an unsafe way. The following logic is currently implemented:
- receive a new state from other party
- sign the state
- respond to the state
- check if the state was valid
Which means currently invalid states are signed. This is a major security flaw.

```
//VPC State version 2 - by bob
	//Read, Sign and send back the vpc state with accept
	vpcStateSigned02, err := newConnToBob.NewVPCStateRead()
	if err != nil {
		_, _ = printer.Printf("\nVpc state read error - %v\n", err)
		return
	}
	aliceID.SetCredentials(testKeystore, alicePassword)
	if err = vpcStateSigned02.AddSign(aliceID, channel.Sender); err != nil {
		_, _ = printer.Printf("\nSigning vpc state error - %v\n", err)
		return
	}
	err = newConnToBob.NewVPCStateRespond(vpcStateSigned02, channel.MessageStatusAccept)
	if err != nil {
		_, _ = printer.Printf("\nVpc state respond error - %v\n", err)
		return
	}

	err = newConnToBob.SetCurrentVPCState(vpcStateSigned02)
	if err != nil {
		_, _ = printer.Printf("\nVpc state error - %v\n", err)
		return
	}
	_, _ = printer.Printf("\nVpc state - %+v\n", vpcStateSigned02)
```

This is because SetCurrentVPCState executes the checks on the state. These checks should be refactored into their own function. It should look like the following: 
```
//VPC State version 2 - by bob
	//Read, Sign and send back the vpc state with accept
	vpcStateSigned02, err := newConnToBob.NewVPCStateRead()
	if err != nil {
		_, _ = printer.Printf("\nVpc state read error - %v\n", err)
		return
	}
        if err := checkState(vpcStateSigned02); err != nil {
		_, _ = printer.Printf("\nVpc state invalid - %v\n", err)
		return
	}
	aliceID.SetCredentials(testKeystore, alicePassword)
	if err = vpcStateSigned02.AddSign(aliceID, channel.Sender); err != nil {
		_, _ = printer.Printf("\nSigning vpc state error - %v\n", err)
		return
	}
	err = newConnToBob.NewVPCStateRespond(vpcStateSigned02, channel.MessageStatusAccept)
	if err != nil {
		_, _ = printer.Printf("\nVpc state respond error - %v\n", err)
		return
	}

	err = newConnToBob.SetCurrentVPCState(vpcStateSigned02)
	if err != nil {
		_, _ = printer.Printf("\nVpc state error - %v\n", err)
		return
	}
	_, _ = printer.Printf("\nVpc state - %+v\n", vpcStateSigned02)
```

**Comment by danielksan81** [comment]
Hi Marius,
good catch, you are right.
The technical validation of the state must happen before sending, therefore the validation checks must be handled separately. The logical handling of the state is use-case dependent and must be done in another way. As the intention of the walkthrough is just to show the current state of possible use, this will not be covered yet.
I would like to welcome you to create a pull request with the corresponding change you described, as my impression is that you already figured out the solution. Would you like to do it? Then I would assign you the issue.

**Comment by RmbRT** [comment]
Kudos to marius!

**Comment by manoranjith** [comment]
Hi @MariusVanDerWijden,
Have you already started working on the solution for this issue ?
If not, then I can start working on it.

**Comment by MariusVanDerWijden** [comment]
@manoranjith I have not. 
Please feel free to work on it.
