### ISSUE TITLE
gometalinter has been deprecated. switch to golangcli-lint.

### ISSUE THREAD

**Issue by manoranjith** [direct-state-transfer/dst-go#4]
[Gometalinter](https://github.com/alecthomas/gometalinter) has been deprecated. Switch to [golangcli-lint](https://github.com/golangci/golangci-lint) that is [faster](https://github.com/golangci/golangci-lint#performance) and offers [better features](https://github.com/golangci/golangci-lint#comparison).

The tasks would be 

- [ ] add config file for golangcli-lint based on existing [gometalinter config](https://github.com/direct-state-transfer/dst-go/blob/develop/build/linterConfig.json).
- [ ] update [build](https://github.com/direct-state-transfer/dst-go/tree/develop/build) package to use golangcli-lint instead of gometalinter.
- [ ] remove [gometalinter config](https://github.com/direct-state-transfer/dst-go/blob/develop/build/linterConfig.json) from the project repo.
- [ ] update the note in [Readme](https://github.com/direct-state-transfer/dst-go#performing-lint).

**Comment by danielksan81** [comment]
At least the build-and-test workflow can now be extended to perform the linting parallel to the unit test.
As I did the setup for the circleci job, I can make a proposal on top of your changes in the same branch.

**Comment by choeppler** [comment]
Did you have a look at https://golangci.com/? Maybe that's also an option, as it seems to be nicely integrated with PRs. Not sure whether it's worth the trade-off of having to maintain two services, though...

**Comment by danielksan81** [comment]
> Did you have a look at https://golangci.com/? Maybe that's also an option, as it seems to be nicely integrated with PRs. Not sure whether it's worth the trade-off of having to maintain two services, though...

Good point. I will check what the benefit will be to use the provided service directly.

**Comment by danielksan81** [comment]
From the feature perspective it seems to be a better option as it will reply to the affected lines directly.
Therefore I would propose to enable the golangci service for the repo to see if it fulfills our criteria.
If it works successfully, we can set the check in the pull requests to required.

**Comment by danielksan81** [comment]
Service is now enabled.
